'use client'
import React from 'react';
import Link from 'next/link';
import { usePathname } from 'next/navigation'
import { getCurrentLocale, getLocalizedPath } from '../lib/i18n'
import { useState, useEffect } from 'react'
import { useRouter } from 'next/navigation'

export default function FAQPage() {
  const pathname = usePathname()
  const currentLocale = getCurrentLocale(pathname)
  const [user, setUser] = useState<any>(null)
  const router = useRouter()

  // 检查用户登录状态
  useEffect(() => {
    const checkAuthStatus = async () => {
      try {
        const response = await fetch('/api/auth/me')
        if (response.ok) {
          const userData = await response.json()
          setUser(userData.user)
        }
      } catch (error) {
        console.error('检查用户状态失败:', error)
      }
    }
    
    checkAuthStatus()
  }, [])

  // 处理"我的作品"点击
  const handleMyWorksClick = (e: React.MouseEvent) => {
    e.preventDefault()
    
    if (!user) {
      // 访客用户，显示注册提示
      const alertMessage = currentLocale === 'zh' 
        ? '请先注册登录后查看您的作品历史' 
        : 'Please register and login to view your work history'
      alert(alertMessage)
      const loginPath = getLocalizedPath('/login', currentLocale)
      router.push(loginPath)
    } else {
      // 注册用户，跳转到作品页面
      const historyPath = getLocalizedPath('/history', currentLocale)
      router.push(historyPath)
    }
  }

  const faqCategories = [
    {
      category: "使用入门",
      icon: "🚀",
      color: "from-blue-500 to-cyan-500",
      questions: [
        {
          question: "我该如何开始使用这款AI图像生成工具？",
          answer: "只需打开网站，选择一个风格模板，输入中文描述，点击「立即生成」即可。新用户注册即可获得10点免费体验点数，无需安装App。"
        },
        {
          question: "支持中文输入吗？我不会写英文Prompt怎么办？",
          answer: "完全支持中文输入！系统内置智能翻译和优化功能，会自动将您的中文描述转换为专业的英文Prompt，并进行AI优化，无需掌握英文提示词写法。"
        },
        {
          question: "为什么我点击生成后没反应或加载很久？",
          answer: "可能原因：1）生成队列较多，请耐心等待；2）网络异常，建议刷新页面重试；3）点数不足，请检查账户余额。如持续无响应超过5分钟，请联系客服。"
        }
      ]
    },
    {
      category: "点数与付费",
      icon: "💰",
      color: "from-green-500 to-emerald-500",
      questions: [
        {
          question: "每次点击生成需要消耗什么？是免费的吗？",
          answer: "每次生成消耗1点数。新用户注册获得10点免费体验。之后可购买点数包：30点(¥9)、100点(¥27)、300点(¥66)，或订阅会员获得更多权益。"
        },
        {
          question: "点数包和会员订阅有什么区别？",
          answer: "点数包：按使用量付费，适合偶尔使用。会员订阅：享受无限生成+专属模板+优先处理+高清导出等特权，适合频繁使用的创作者。"
        },
        {
          question: "是否支持退款或点数找回？",
          answer: "虚拟点数一经使用不可退回。如遇系统异常导致多次失败扣点，可提供截图申请人工处理补点。未使用的点数包支持7天内申请退款。"
        },
        {
          question: "支付安全吗？支持哪些支付方式？",
          answer: "支持支付宝、微信支付，均采用官方安全支付通道，资金安全有保障。支付成功后点数立即到账，支持开具电子发票。"
        }
      ]
    },
    {
      category: "功能使用",
      icon: "🎨",
      color: "from-purple-500 to-pink-500",
      questions: [
        {
          question: "我可以自定义风格或Prompt吗？",
          answer: "支持两种模式：1）简单模式：选择风格模板+中文描述；2）高级模式：完全自定义Prompt、调节参数（图像尺寸、风格强度等）。"
        },
        {
          question: "为什么我看不到某些风格模板？",
          answer: "部分高级模板仅对会员开放。免费用户可使用基础模板，会员可享受全部18+专业模板，包括商用级、艺术级等高端风格。"
        },
        {
          question: "生成的图像带有水印吗？",
          answer: "所有用户生成的图像均为无水印高清版本。支持直接下载保存，可用于个人创作、社交分享等用途。"
        },
        {
          question: "如何提高生成效果？有什么技巧吗？",
          answer: "技巧：1）描述要具体详细；2）选择合适的风格模板；3）开启AI优化功能；4）使用高级参数调节；5）多尝试不同的关键词组合。"
        }
      ]
    },
    {
      category: "作品管理",
      icon: "📁",
      color: "from-orange-500 to-red-500",
      questions: [
        {
          question: "我生成的图像在哪里查看？可以保存吗？",
          answer: "登录后，所有生成图像将自动保存在「我的作品」中。支持分类管理、添加标签、收藏、下载、分享，还可以基于历史作品重新生成。"
        },
        {
          question: "可以批量下载我的作品吗？",
          answer: "支持！在「我的作品」页面，可以勾选多张图片进行批量操作：批量下载、批量收藏、批量添加标签或批量删除。"
        },
        {
          question: "作品会保存多久？会丢失吗？",
          answer: "会员用户作品永久保存，免费用户保存90天。建议及时下载重要作品到本地。我们承诺不会删除付费用户的作品数据。"
        }
      ]
    },
    {
      category: "商用授权",
      icon: "📄",
      color: "from-indigo-500 to-purple-500",
      questions: [
        {
          question: "生成的图像我可以商用吗？",
          answer: "个人创作、社交分享完全免费。商业用途建议升级商用授权：会员用户享受基础商用权限，企业用户可申请扩展商用授权。"
        },
        {
          question: "如何获得商用授权证明？",
          answer: "会员用户可在「我的作品」中为特定图片申请商用授权证明。企业用户可联系客服获得批量授权协议和授权书。"
        },
        {
          question: "商用时需要标注来源吗？",
          answer: "个人使用无需标注。商业用途建议标注'Generated by ARTBUD.SPACE'，有助于获得更好的技术支持和优先服务。"
        }
      ]
    },
    {
      category: "技术支持",
      icon: "🛠️",
      color: "from-teal-500 to-cyan-500",
      questions: [
        {
          question: "支持什么图像尺寸和格式？",
          answer: "支持多种尺寸：方形(512×512)、横向(768×512)、竖向(512×768)。输出格式为高清PNG，支持下载为JPG。会员可享受更大尺寸选项。"
        },
        {
          question: "生成失败了怎么办？点数会被扣除吗？",
          answer: "生成失败不会扣除点数。常见失败原因：描述包含违规内容、网络超时、服务器繁忙。系统会自动重试，失败后可免费重新生成。"
        },
        {
          question: "可以在手机上使用吗？",
          answer: "完全支持！网站采用响应式设计，在手机、平板、电脑上均可正常使用。建议使用Chrome、Safari等现代浏览器获得最佳体验。"
        },
        {
          question: "如何联系客服或反馈问题？",
          answer: "多种方式：1）页面内「给我留言」按钮；2）发送邮件至support@artbud.space；3）微信群客服；4）工作时间9:00-18:00提供在线支持。"
        }
      ]
    }
  ];

  return (
    <div className="min-h-screen bg-gradient-to-b from-zinc-900 to-zinc-800 text-white">
      <div className="max-w-7xl mx-auto w-full py-8 px-4">
        {/* Hero Section - 标题区 */}
        <section className="flex flex-col items-center justify-center text-center mb-12" id="faq-hero">
          <div className="flex items-center justify-center gap-4 mb-6">
            <div className="w-16 h-16 bg-gradient-to-br from-blue-500 to-purple-600 rounded-2xl flex items-center justify-center shadow-2xl">
              <svg className="w-8 h-8 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8.228 9c.549-1.165 2.03-2 3.772-2 2.21 0 4 1.343 4 3 0 1.4-1.278 2.575-3.006 2.907-.542.104-.994.54-.994 1.093m0 3h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
              </svg>
            </div>
            <h1 className="text-5xl md:text-6xl font-black bg-gradient-to-r from-cyan-300 via-blue-400 to-purple-500 bg-clip-text text-transparent">
              常见问题
            </h1>
          </div>
          <p className="text-xl text-gray-300 max-w-3xl leading-relaxed mb-4">
            快速找到您关心的问题解答，让您更好地使用 <span className="text-orange-400 font-semibold">ARTBUD.SPACE</span> AI图像生成工具
          </p>
          <div className="flex items-center gap-2 text-sm text-blue-400 bg-blue-900/20 px-4 py-2 rounded-full border border-blue-500/30">
            <svg className="w-4 h-4" fill="currentColor" viewBox="0 0 20 20">
              <path fillRule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z" clipRule="evenodd" />
            </svg>
            {faqCategories.reduce((total, category) => total + category.questions.length, 0)} 个常见问题，6大类别
          </div>
        </section>

        {/* FAQ Categories */}
        {faqCategories.map((category, categoryIndex) => (
          <section key={categoryIndex} className="mb-12">
            <div className="bg-gradient-to-r from-zinc-800/80 to-zinc-700/80 backdrop-blur-sm rounded-2xl py-8 px-8 border border-zinc-600/30 shadow-2xl">
              {/* Category Header */}
              <div className="flex items-center gap-4 mb-6">
                <div className={`w-12 h-12 bg-gradient-to-r ${category.color} rounded-xl flex items-center justify-center text-2xl shadow-lg`}>
                  {category.icon}
                </div>
                <div>
                  <h2 className="text-2xl font-bold text-white">{category.category}</h2>
                  <p className="text-gray-400 text-sm">{category.questions.length} 个问题</p>
                </div>
              </div>

              {/* Questions */}
              <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
                {category.questions.map((item, index) => (
                  <div 
                    key={index} 
                    className="group bg-gradient-to-br from-zinc-700/60 to-zinc-800/60 backdrop-blur-sm p-6 rounded-xl border border-zinc-600/50 hover:border-blue-400/70 transition-all duration-300 transform hover:scale-102 hover:shadow-lg hover:shadow-blue-500/10"
                  >
                    <div className="flex items-start gap-4 mb-4">
                      <div className="flex-shrink-0 w-8 h-8 bg-gradient-to-r from-blue-500 to-purple-500 rounded-full flex items-center justify-center text-white font-bold text-sm shadow-lg">
                        Q
                      </div>
                      <h3 className="text-lg font-bold text-white group-hover:text-blue-300 transition-colors">
                        {item.question}
                      </h3>
                    </div>
                    <div className="ml-12">
                      <p className="text-gray-300 leading-relaxed text-sm">
                        {item.answer}
                      </p>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </section>
        ))}

        {/* Quick Action Cards - 快速操作卡片 */}
        <section className="mb-8">
          <div className="bg-gradient-to-r from-zinc-800/60 to-zinc-700/60 backdrop-blur-sm rounded-xl py-6 px-6 border border-zinc-600/20">
            <h3 className="text-lg font-bold text-green-400 mb-4 flex items-center gap-2">
              <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z" />
              </svg>
              快速上手指南
            </h3>
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
              <Link href={getLocalizedPath('/', currentLocale)} className="group bg-blue-900/20 hover:bg-blue-900/40 border border-blue-500/30 rounded-lg p-4 transition-all duration-300 hover:scale-105">
                <div className="text-2xl mb-2">🚀</div>
                <div className="text-blue-300 font-medium mb-1">开始创作</div>
                <div className="text-gray-400 text-xs">立即体验AI生成</div>
              </Link>
              
              <Link href={getLocalizedPath('/pricing', currentLocale)} className="group bg-green-900/20 hover:bg-green-900/40 border border-green-500/30 rounded-lg p-4 transition-all duration-300 hover:scale-105">
                <div className="text-2xl mb-2">💎</div>
                <div className="text-green-300 font-medium mb-1">查看价格</div>
                <div className="text-gray-400 text-xs">选择合适套餐</div>
              </Link>
              
              <Link href={getLocalizedPath('/features', currentLocale)} className="group bg-purple-900/20 hover:bg-purple-900/40 border border-purple-500/30 rounded-lg p-4 transition-all duration-300 hover:scale-105">
                <div className="text-2xl mb-2">⚡</div>
                <div className="text-purple-300 font-medium mb-1">功能介绍</div>
                <div className="text-gray-400 text-xs">了解全部功能</div>
              </Link>
              
              <button 
                onClick={handleMyWorksClick}
                className="group bg-orange-900/20 hover:bg-orange-900/40 border border-orange-500/30 rounded-lg p-4 transition-all duration-300 hover:scale-105"
              >
                <div className="text-2xl mb-2">📁</div>
                <div className="text-orange-300 font-medium mb-1">我的作品</div>
                <div className="text-gray-400 text-xs">管理创作内容</div>
              </button>
            </div>
          </div>
        </section>

        {/* 返回首页按钮 */}
        <div className="text-center">
          <Link
            href={getLocalizedPath('/', currentLocale)}
            className="inline-flex items-center gap-2 bg-gradient-to-r from-blue-500 to-purple-500 hover:from-purple-500 hover:to-blue-500 text-white font-semibold px-6 py-3 rounded-lg transition-all duration-300 transform hover:scale-105"
          >
            <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011 1v4a1 1 0 001 1m-6 0h6" />
            </svg>
            返回首页
          </Link>
        </div>
      </div>
    </div>
  );
}